# Generated by Django 6.1.1 on 2026-09-16 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocalDeVoo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('cidade', models.CharField(default='São Pedro', max_length=120)),
                ('estado', models.CharField(default='SP', max_length=2)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('altitude_metros', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
