# Generated by Django 6.1.1 on 2026-09-21 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ItaqueriAero', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('fonte', models.CharField(choices=[('CSPVL_OBSERVADO', 'Estação CSPVL (observado)'), ('NASA_POWER_MERRA2', 'NASA POWER (reanalise)')], max_length=30)),
                ('temperatura_media_c', models.FloatField(blank=True, null=True)),
                ('temperatura_maxima_c', models.FloatField(blank=True, null=True)),
                ('hora_maxima', models.TimeField(blank=True, null=True)),
                ('temperatura_minima_c', models.FloatField(blank=True, null=True)),
                ('hora_minima', models.TimeField(blank=True, null=True)),
                ('chuva_mm', models.FloatField(blank=True, null=True)),
                ('umidade_media_pct', models.FloatField(blank=True, null=True)),
                ('vento_medio_kmh', models.FloatField(blank=True, null=True)),
                ('vento_maximo_kmh', models.FloatField(blank=True, null=True)),
                ('hora_vento_maximo', models.TimeField(blank=True, null=True)),
                ('direcao_vento_graus', models.FloatField(blank=True, null=True)),
                ('url_origem', models.URLField(blank=True, max_length=500)),
                ('observacao', models.TextField(blank=True)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_diario', to='ItaqueriAero.localdevoo')),
            ],
            options={
                'verbose_name': 'Histórico diário',
                'verbose_name_plural': 'Histórico diário',
                'ordering': ['-data'],
                'unique_together': {('local', 'data', 'fonte')},
            },
        ),
    ]
